/**
 * Recommendation Engine + Approval Queue.
 *
 * Every recommendation is generated by a deterministic policy over engine
 * outputs — the AI may narrate them but never invents them. Each one states
 * its problem, financial impact, reasoning, confidence, and risk, and any
 * estimated figure names the assumption it was computed under. Nothing here
 * moves money: approving a recommendation records a decision and emits an
 * audited event; execution stays with the human.
 */

import { Paise, ZERO, add, sub, sum, mulRatio, formatINR } from "./money.js";
import { Statements } from "./statements.js";
import { CashFlowIntelligence } from "./cashflow.js";
import { InvoiceEngine } from "./invoices.js";
import { GstEngine } from "./gst.js";
import { RecurringDetector } from "./recurring.js";
import { EventBus } from "./events.js";

export type Confidence = "high" | "medium" | "low";
export type RiskLevel = "low" | "medium" | "high";
export type RecommendationStatus = "pending" | "approved" | "dismissed";

export interface Recommendation {
  readonly id: string;
  readonly orgId: string;
  readonly kind: string; // "overdue_invoices" | "gst_filing" | ...
  readonly title: string;
  readonly problem: string;
  readonly reason: string;
  readonly requiredAction: string;
  readonly impact: Paise | null; // the money at stake, when quantifiable
  readonly estimatedSavings: Paise | null; // with the assumption stated in `reason`
  readonly confidence: Confidence;
  readonly risk: RiskLevel;
  readonly requiresApproval: boolean; // money movement / regulatory submission
  readonly status: RecommendationStatus;
  readonly generatedAt: string;
  readonly decidedBy: string | null;
}

export class RecommendationError extends Error {
  override name = "RecommendationError";
}

export class RecommendationEngine {
  private recs = new Map<string, Recommendation>(); // keyed by dedupe id — regeneration preserves decisions
  private counter = 0;

  constructor(
    public readonly orgId: string,
    private statements: Statements,
    private cashflow: CashFlowIntelligence,
    private invoices: InvoiceEngine,
    private gst: GstEngine,
    private recurring: RecurringDetector,
    private bus: EventBus,
  ) {}

  /** Re-run all policies as of a date. Existing decisions (approved/dismissed) are preserved. */
  generate(asOf: string, periodFrom: string): readonly Recommendation[] {
    const found: Array<Omit<Recommendation, "id" | "orgId" | "status" | "generatedAt" | "decidedBy"> & { dedupe: string }> = [];

    // 1. Overdue invoices — chase the money you already earned.
    const overdue = this.invoices.overdue(asOf);
    if (overdue.length > 0) {
      const total = sum(overdue.map((o) => o.outstanding));
      const oldest = overdue[0]!;
      found.push({
        dedupe: "overdue_invoices",
        kind: "overdue_invoices",
        title: `Follow up on ${overdue.length} overdue invoice${overdue.length > 1 ? "s" : ""}`,
        problem: `${formatINR(total)} is stuck in overdue receivables; the oldest (${oldest.invoice.number}, ${oldest.invoice.customer}) is ${oldest.daysOverdue} days past due.`,
        reason: "Receivables lose collectability as they age; a structured reminder cadence recovers most invoices under 60 days old.",
        requiredAction: "Send payment reminders to the listed customers; escalate anything past 60 days.",
        impact: total,
        estimatedSavings: null,
        confidence: "high",
        risk: "low",
        requiresApproval: false,
      });
    }

    // 2. GST filing due within 10 days — regulatory, always needs explicit approval.
    const dueSoon = this.gst.upcomingFilings(asOf).filter((f) => f.daysLeft >= 0 && f.daysLeft <= 10);
    for (const f of dueSoon) {
      const [py, pm] = f.period.split("-").map(Number) as [number, number];
      const lastDay = new Date(Date.UTC(py, pm, 0)).getUTCDate();
      const pos = this.gst.position(`${f.period}-01`, `${f.period}-${String(lastDay).padStart(2, "0")}`);
      found.push({
        dedupe: `gst_${f.form}_${f.period}`,
        kind: "gst_filing",
        title: `${f.form} for ${f.period} due in ${f.daysLeft} day${f.daysLeft === 1 ? "" : "s"}`,
        problem: `${f.form} (${f.note.toLowerCase()}) is due ${f.dueDate}; net GST payable for the period is ${formatINR(pos.netPayable)}.`,
        reason: `Output tax ${formatINR(pos.outputTax)} minus input tax credit ${formatINR(pos.inputTaxCredit)} for ${f.period}. Late filing attracts fees and interest.`,
        requiredAction: `Review the prepared ${f.form} figures and approve submission before ${f.dueDate}.`,
        impact: pos.netPayable,
        estimatedSavings: null,
        confidence: "high",
        risk: "medium",
        requiresApproval: true, // regulatory submission — never automatic
      });
    }

    // 3. Short runway — the one problem that kills companies.
    const metrics = this.cashflow.metrics(asOf);
    if (metrics.runwayDays !== null && metrics.runwayDays < 180 && metrics.monthlyNetBurn !== null) {
      found.push({
        dedupe: "short_runway",
        kind: "short_runway",
        title: `Runway is ${metrics.runwayDays} days — below the 6-month floor`,
        problem: `At the current net burn of ${formatINR(metrics.monthlyNetBurn)}/month, cash lasts ${metrics.runwayDays} days.`,
        reason: metrics.note,
        requiredAction: "Cut discretionary spend, accelerate collections, or line up funding within the quarter.",
        impact: metrics.monthlyNetBurn,
        estimatedSavings: null,
        confidence: "high",
        risk: "high",
        requiresApproval: false,
      });
    }

    // 4. Subscription review — recurring committed spend worth auditing.
    const rec = this.recurring.summary(asOf);
    if (rec.subscriptionMonthly > 0n) {
      const annual = mulRatio(rec.subscriptionMonthly, 12n, 1n);
      found.push({
        dedupe: "subscription_review",
        kind: "subscription_review",
        title: `${formatINR(rec.subscriptionMonthly)}/month goes to subscriptions`,
        problem: `Detected recurring subscription spend of ${formatINR(rec.subscriptionMonthly)}/month (${formatINR(annual)}/year) across ${rec.items.filter((i) => i.isSubscription).length} services.`,
        reason: "Recurring tools accumulate silently; each detected subscription is listed with its annualized cost so unused seats and duplicate tools can be cancelled.",
        requiredAction: "Review the subscription list and cancel anything unused.",
        impact: annual,
        estimatedSavings: null, // savings depend on which tools the user cancels — not guessed
        confidence: "medium",
        risk: "low",
        requiresApproval: false,
      });
    }

    // 5. Idle cash — excess beyond a 6-month buffer could earn stated FD interest.
    if (metrics.monthlyNetBurn !== null && metrics.monthlyNetBurn > 0n) {
      const buffer = mulRatio(metrics.monthlyNetBurn, 6n, 1n);
      const excess = sub(metrics.cashOnHand, buffer);
      if (excess > 0n) {
        const annualInterest = mulRatio(excess, 6n, 100n); // stated assumption: 6% p.a. FD rate
        found.push({
          dedupe: "idle_cash",
          kind: "idle_cash",
          title: `${formatINR(excess)} of cash is idle beyond a 6-month buffer`,
          problem: `Cash on hand is ${formatINR(metrics.cashOnHand)}; a 6-month burn buffer needs only ${formatINR(buffer)}.`,
          reason: `Assumption: excess parked in a fixed deposit at 6% p.a. would earn about ${formatINR(annualInterest)} a year. Rate is an assumption, not a quote.`,
          requiredAction: "Consider a sweep-in FD for the excess; keep the 6-month buffer liquid.",
          impact: excess,
          estimatedSavings: annualInterest,
          confidence: "medium",
          risk: "low",
          requiresApproval: true, // moving money — never automatic
        });
      }
    }

    // 6. Expense spike — current month vs trailing average, per account.
    const spikes = this.detectSpikes(asOf);
    for (const s of spikes) {
      found.push({
        dedupe: `spike_${s.accountId}_${asOf.slice(0, 7)}`,
        kind: "expense_spike",
        title: `${s.name} spend jumped to ${formatINR(s.current)} this month`,
        problem: `${s.name} is at ${formatINR(s.current)} for ${asOf.slice(0, 7)} vs a trailing 3-month average of ${formatINR(s.average)}.`,
        reason: "A month-over-month jump above 50% on a material category is worth a look — it is either a plan change or a mistake.",
        requiredAction: `Check the ${s.name} transactions for this month and confirm they are expected.`,
        impact: sub(s.current, s.average),
        estimatedSavings: null,
        confidence: "medium",
        risk: "medium",
        requiresApproval: false,
      });
    }

    // Upsert: new recs get created; existing ones keep their status/decision.
    const now = new Date().toISOString();
    for (const f of found) {
      const existing = this.recs.get(f.dedupe);
      if (existing) {
        this.recs.set(f.dedupe, { ...existing, ...stripDedupe(f), generatedAt: existing.generatedAt });
      } else {
        const rec: Recommendation = {
          ...stripDedupe(f),
          id: `rec_${this.orgId}_${++this.counter}`,
          orgId: this.orgId,
          status: "pending",
          generatedAt: now,
          decidedBy: null,
        };
        this.recs.set(f.dedupe, rec);
        this.emit("recommendation.created", "system", { id: rec.id, kind: rec.kind, title: rec.title });
      }
    }
    return this.all();
  }

  all(): readonly Recommendation[] {
    return [...this.recs.values()];
  }

  pending(): readonly Recommendation[] {
    return this.all().filter((r) => r.status === "pending");
  }

  approve(id: string, actor: string): Recommendation {
    return this.decide(id, actor, "approved");
  }

  dismiss(id: string, actor: string): Recommendation {
    return this.decide(id, actor, "dismissed");
  }

  private decide(id: string, actor: string, status: "approved" | "dismissed"): Recommendation {
    const entry = [...this.recs.entries()].find(([, r]) => r.id === id);
    if (!entry) throw new RecommendationError(`Unknown recommendation ${id}`);
    const [key, rec] = entry;
    if (rec.status !== "pending") throw new RecommendationError(`Recommendation ${id} is already ${rec.status}`);
    const next: Recommendation = { ...rec, status, decidedBy: actor };
    this.recs.set(key, next);
    this.emit(`recommendation.${status}`, actor, { id, kind: rec.kind, title: rec.title });
    return next;
  }

  private detectSpikes(asOf: string): Array<{ accountId: string; name: string; current: Paise; average: Paise }> {
    const month = asOf.slice(0, 7);
    const currentPl = this.statements.profitAndLoss(`${month}-01`, asOf);
    const out: Array<{ accountId: string; name: string; current: Paise; average: Paise }> = [];
    for (const line of currentPl.expenses) {
      // trailing 3 full months before the current one
      let trailing: Paise = ZERO;
      for (let i = 1; i <= 3; i++) {
        const w = monthWindow(asOf, -i);
        const pl = this.statements.profitAndLoss(w.from, w.to);
        const match = pl.expenses.find((e) => e.accountId === line.accountId);
        trailing = add(trailing, match?.amount ?? ZERO);
      }
      const average = mulRatio(trailing, 1n, 3n);
      if (average <= 0n) continue; // new categories aren't spikes
      // spike = current > 1.5 × average and the jump is at least ₹10,000
      if (line.amount * 2n > average * 3n && sub(line.amount, average) >= 1_000_000n) {
        out.push({ accountId: line.accountId, name: line.name, current: line.amount, average });
      }
    }
    return out;
  }

  private emit(type: string, actor: string, payload: Record<string, unknown>): void {
    this.bus.emit({ orgId: this.orgId, type, at: new Date().toISOString(), actor, payload });
  }
}

type RecFields = Omit<Recommendation, "id" | "orgId" | "status" | "generatedAt" | "decidedBy">;

const stripDedupe = (f: RecFields & { dedupe: string }): RecFields => {
  const { dedupe: _dedupe, ...rest } = f;
  return rest;
};

const monthWindow = (asOf: string, offset: number): { from: string; to: string } => {
  const [y, m] = asOf.split("-").map(Number) as [number, number];
  const total = y * 12 + (m - 1) + offset;
  const ty = Math.floor(total / 12);
  const tm = ((total % 12) + 12) % 12;
  const lastDay = new Date(Date.UTC(ty, tm + 1, 0)).getUTCDate();
  const mm = String(tm + 1).padStart(2, "0");
  return { from: `${ty}-${mm}-01`, to: `${ty}-${mm}-${String(lastDay).padStart(2, "0")}` };
};
